/**
 * Generates web/src/poster-qr.ts — an inlined SVG QR code of the Guruji
 * GitHub Pages URL, for the printable classroom poster (/poster route).
 *
 * The `qrcode` npm package is VENDORED at web/vendor/qrcode (with its
 * dijkstrajs + pngjs deps) instead of a normal devDependency, because CI
 * deploys with `pnpm install --frozen-lockfile` and there is no way to
 * regenerate pnpm-lock.yaml from this environment. The vendored copy runs
 * fully offline — no network, no external API at runtime.
 *
 * Runs automatically via the `prebuild` npm script; safe to run by hand too:
 *   node scripts/make-qr.mjs
 */
import { createRequire } from "node:module";
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const webDir = join(here, "..");
const require = createRequire(import.meta.url);

// Vendored qrcode (server build exposes toString with type:"svg").
const QRCode = require(join(webDir, "vendor", "qrcode", "lib", "server.js"));

const URL = "https://devilking7x.github.io/guruji/";

const svg = await QRCode.toString(URL, {
  type: "svg",
  width: 480,
  margin: 1,
  color: { dark: "#1e1b2e", light: "#ffffff" },
});

const out = `// AUTO-GENERATED by web/scripts/make-qr.mjs — do not edit by hand.
// Offline SVG QR code of ${URL} (regenerated on every build).
export const POSTER_QR_SVG: string = ${JSON.stringify(svg)};
export const POSTER_QR_URL = ${JSON.stringify(URL)};
`;

writeFileSync(join(webDir, "src", "poster-qr.ts"), out);
console.log(`poster-qr.ts written (${svg.length} chars of SVG)`);
